spring:
  profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
  datasource:
    url: jdbc:sqlite:test.db
    driverClassName: org.sqlite.JDBC
server:
  port: 8081

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/